### ISSUE TITLE
Upgrade to selenium-webdriver 2.48.x to fix problems for node 4

### ISSUE THREAD

**Issue by avdv** [tobli/browsertime#95]
On node 4.x the build of ws @ 0.7.x fails because of a compilation error for utf-8-validate. The build problem is fixed in ws@0.8.0.

To get the fix into browsertime, the dependency of the selenium-webdriver would need to be updated.

**Comment by anselmbradford** [comment]
:+1:

**Comment by tobli** [comment]
Hi! Thanks for reporting, sorry for not getting back earlier.
I'll bump to 2.47 for now. It retains compatibility with node 0.12, while allowing node 4.x to work. Going forward I'm working on a separate 1.0 branch, which is essentially a re-write. It uses promises for managing async work, and should hopefully make lots of async related issues go away. There's a proper test suite to try and verify as many scenarios as possible. The 1.0 branch partially uses ES6 syntax and will be node 4+ only. The plan is to adopt more proper semantic versioning after 1.0 is out.

It does mean lagging behind on selenium-webdriver for a little while, but should avoid trouble for current node 0.12 users and allow me to spend the time I have right now on 1.0. I hope that's a reasonable tradeoff.

**Comment by tobli** [comment]
Browsertime 0.12 with selenium-webdriver 2.47 is out now, and sitespeed.io 3.11.1 that includes it. Closing this now, but let me know if it doesn't work out for you. Thanks!
